import { Injectable, inject, signal, computed, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type Lang = 'fr' | 'ar' | 'en';

export const LANGUAGES: { code: Lang; label: string; flag: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'fr', label: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'en', label: 'English',  flag: '🇬🇧', dir: 'ltr' },
  { code: 'ar', label: 'العربية',  flag: '🇲🇦', dir: 'rtl' },
];

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  fr: {
    // Navbar
    sell:           'Vendre',
    profile:        'Profil',
    register:       "S'inscrire",
    createProfile:  'Créer mon profil',
    alreadyAccount: "J'ai déjà un compte",
    myProfile:      'Mon profil',
    myShop:         'Ma boutique',
    logout:         'Déconnexion',
    location:       'Casablanca • Particulier',

    // Auth modal — shared
    back:           'Retour',
    next:           'Suivant',
    validate:       'Valider',
    loading:        'Chargement…',
    orSeparator:    'ou',

    // Auth modal — login
    loginTitle:     'Connexion',
    loginSubtitle:  'Connectez-vous avec votre numéro ou e-mail',
    identifierLabel: 'Téléphone ou e-mail',
    identifierPlaceholder: '+212 6XX XXX XXX ou email@exemple.ma',
    passwordLabel:  'Mot de passe',
    passwordPlaceholder: '••••••••',
    loginBtn:       'Se connecter',
    noAccount:      'Pas encore de compte ?',
    createAccount:  'Créer un compte',
    loginWithOtp:   'Se connecter par SMS',

    // Home — hero
    heroBadge:      'Petites annonces',
    heroTitle1:     'Trouvez,',
    heroTitle2:     'vendez',
    heroSubtitle:   'Des milliers d\'annonces immobilier, voitures, emploi et plus. Publiez gratuitement en quelques secondes.',
    heroSearch:     'Appartement, Clio, iPhone…',
    statAds:        '+40 000',
    statShops:      '+800',
    statFree:       'Gratuit',
    seeAll:         'Voir tout',
    copyright:      '© 2026 Daba. Tous droits réservés.',
    madeIn:         'Fait avec ❤️',

    // Home — features
    feat1Title: 'Photos & Vidéos',
    feat1Desc:  'Jusqu\'à 10 photos et vidéos YouTube pour vos annonces.',
    feat2Title: 'Connexion par téléphone',
    feat2Desc:  'Pas de mot de passe — recevez un code par SMS ou WhatsApp.',
    feat3Title: 'Boutiques Pro',
    feat3Desc:  'Créez votre boutique pro et gérez toutes vos annonces.',
    feat4Title: 'Recherche avancée',
    feat4Desc:  'Filtrez par ville, prix, catégorie et attributs spécifiques.',

    // Home — categories
    catImmobilier:   'Immobilier',
    catAutomobile:   'Véhicules',
    catEmploi:       'Emploi',
    catElectronique: 'Électronique',
    catMaison:       'Maison',
    catMode:         'Mode',
    catLoisirs:      'Loisirs',
    catServices:     'Services',

    sectionTrending:   'Tendances du moment',
    sectionCars:       'Changer de voiture',
    sectionRealEstate: 'Immobilier à la une',
    seeAllAds:         'Voir toutes les annonces',
    searchTitle:    'Recherchez un article, une ville ou une boutique',
    searchSubtitle: "Commencez votre recherche parmi des milliers d'annonces locales.",
    searchPlaceholder: 'Recherchez un article, une ville ou une boutique',
    searchButton: 'Chercher',
    allCities: 'Toutes les villes',
    statsActiveAds: 'annonces actives',
    statsProShops: 'boutiques pro',
    statsFree: 'pour tous',
    exploreByCategory: 'Explorer par catégorie',
    whyTitle: 'Pourquoi Daba ?',
    whySubtitle: 'Simple, rapide et fait pour le Maroc.',
    ctaBadge: 'Démarrez maintenant',
    ctaTitle: 'Vendez en quelques minutes',
    ctaDesc: 'Publiez votre annonce gratuitement avec photos, ou créez une boutique pro pour gérer votre stock. Connexion par numéro de téléphone — pas de mot de passe.',
    ctaPostAd: 'Déposer une annonce gratuite',
    ctaOpenShop: 'Créer une boutique pro',
    adsPublished: 'annonces publiées',
    shopsActive: 'boutiques actives',
    freeForPosting: 'gratuit pour déposer',
    footerDesc: 'Le site de petites annonces et des grandes opportunités. Simple, rapide, gratuit.',
    footerCategories: 'Catégories',
    footerAccount: 'Compte',
    footerLogin: 'Se connecter',
    footerPostAd: 'Publier une annonce',
    footerProShops: 'Boutiques pro',
    vehicles: 'Véhicules',
    realEstate: 'Immobilier',
    jobsCategory: 'Emploi',
    promoEyebrow: 'Faites tourner les bonnes affaires',
    promoTitle: 'Vendez quelque chose. Achetez ce dont vous avez besoin.',
    promoText: 'Publiez en quelques minutes et touchez des acheteurs locaux pour vos objets, services et offres.',
    sellNow: 'Vendre',
    browseAds: 'Acheter',
    topAdsTitle: 'Parcourez les meilleures annonces',
    topAdsSubtitle: 'Découvrez des offres de véhicules, immobilier et emploi.',
    viewAllCategories: 'Voir toutes les catégories',
    footerBrandText: 'Transformez vos objets inutilisés en bonnes affaires, simplement.',
    footerBrand: 'Daba',
    aboutUs: 'À propos',
    press: 'Presse',
    careers: 'Carrières',
    sustainability: 'Durabilité',
    support: 'Support',
    help: 'Aide',
    helpCenter: "Centre d'aide",
    communityGuidelines: 'Règles de la communauté',
    securityTips: 'Conseils de sécurité',
    legal: 'Légal',
    legalSection: 'Informations légales',
    legalNotice: 'Mentions légales',
    terms: 'Conditions',
    privacy: 'Confidentialité',
    cookies: 'Cookies',
    pro: 'Daba Pro',
    followUs: 'Suivez-nous',

    // Auth modal — register step 1 (credentials)
    registerTitle:     'Créer un compte',
    registerSubtitle:  'Renseignez vos informations de connexion',
    phoneLabel:        'Numéro de téléphone',
    phonePlaceholder:  '+212 6XX XXX XXX',
    emailLabel:        'Adresse e-mail',
    emailPlaceholder:  'email@example.com',
    optional:          '(optionnel)',
    confirmPasswordLabel: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: '••••••••',
    hasAccount:        'Déjà un compte ?',
    login:             'Se connecter',

    // Auth modal — register step 2 (identity)
    identityTitle:    'Votre identité',
    identitySubtitle: 'Comment souhaitez-vous être affiché ?',
    displayNameLabel: 'Nom affiché',
    displayNamePlaceholder: 'Ex : Ahmed Benali',

    // Auth modal — register step 3 (address)
    addressTitle:      'Votre adresse',
    addressSubtitle:   'Optionnel — utilisée pour localiser vos annonces',
    addressLabel:      'Adresse',
    addressPlaceholder: '12 rue Mohammed V',
    cityLabel:         'Ville',
    cityPlaceholder:   'Casablanca',
    postalCodeLabel:   'Code postal',
    postalCodePlaceholder: '20000',
    countryLabel:      'Pays',
    finishBtn:         'Créer mon compte',

    // OTP step
    sendCode:         'Recevoir le code',
    otpTitle:         'Vérification',
    otpSentTo:        'Code envoyé au',
    otpLabel:         'Code à 6 chiffres',
    otpPlaceholder:   '• • • • • •',
    resendCode:       'Renvoyer le code',

    // Ads page
    allAds:            'Toutes les annonces',
    searchAds:         'Rechercher des annonces…',
    filters:           'Filtres',
    filterCategory:    'Catégorie',
    filterSubcategory: 'Sous-catégorie',
    filterCity:        'Ville',
    filterPriceRange:  'Fourchette de prix',
    filterMinPrice:    'Min (Dh)',
    filterMaxPrice:    'Max (Dh)',
    applyFilters:      'Appliquer',
    resetFilters:      'Réinitialiser',
    sortBy:            'Trier par',
    sortNewest:        'Plus récentes',
    sortPriceAsc:      'Prix croissant',
    sortPriceDesc:     'Prix décroissant',
    noAdsFound:        'Aucune annonce trouvée',
    noAdsFoundSub:     'Essayez de modifier vos filtres ou votre recherche.',
    currency:          'Dh',
    listingCount:      'annonce(s)',
    priceNegotiable:   'Prix à discuter',
    allSubcategories:  'Toutes les sous-catégories',
    allCategories:     'Toutes les catégories',
    contactSeller:     'Contacter le vendeur',
    backToResults:     'Retour aux annonces',
    adNotFound:        'Annonce introuvable',
    adNotFoundSub:     'Cette annonce n\'existe plus ou a été supprimée.',
    adDescription:     'Description',
    postedOn:          'Publié le',
    views:             'vues',
    share:             'Partager',

    // Post Ad
    postAdTitle:        'Déposer une annonce',
    postAdSubtitle:     'Remplissez les informations ci-dessous pour publier votre annonce.',
    postAdCategory:     'Catégorie',
    postAdSubcategory:  'Sous-catégorie',
    postAdSelectCat:    'Choisir une catégorie',
    postAdSelectSub:    'Choisir une sous-catégorie',
    postAdAdTitle:      'Titre de l\'annonce',
    postAdTitlePlaceholder: 'Ex : iPhone 14 Pro Max 256 Go',
    postAdDescription:  'Description',
    postAdDescPlaceholder: 'Décrivez votre article en détail…',
    postAdPrice:        'Prix (MAD)',
    postAdPricePlaceholder: 'Ex : 1500',
    postAdPriceFree:    'Laisser vide si gratuit',
    postAdCity:         'Ville',
    postAdSelectCity:   'Choisir une ville',
    postAdSubmit:       'Publier l\'annonce',
    postAdSuccess:      'Annonce publiée avec succès !',
    postAdLoginRequired: 'Vous devez être connecté pour publier une annonce.',
    errCatRequired:     'Veuillez choisir une catégorie',
    errTitleRequired:   'Veuillez saisir un titre',
    errCityRequired:    'Veuillez choisir une ville',

    // Errors
    errInvalidPhone:    'Numéro de téléphone invalide',
    errInvalidEmail:    'Adresse e-mail invalide',
    errPasswordMin:     'Le mot de passe doit contenir au moins 8 caractères',
    errPasswordMatch:   'Les mots de passe ne correspondent pas',
    errDisplayName:     'Veuillez saisir un nom',
    errIdentifier:      'Téléphone ou e-mail requis',
    errInvalidOtp:      'Code incorrect ou expiré',
    errNetwork:         'Erreur réseau, réessayez',
    errPhoneOrEmail:    'Téléphone ou e-mail requis',
    errCredentials:     'Identifiants incorrects',

    // Warnings
    testingWarning: 'Ce site web est destiné aux tests et le contenu n\'est pas des annonces réelles',
    maintenanceWarning: 'Maintenance en cours - aucune nouvelle annonce ne peut être publiée',
  },

  en: {
    // Navbar
    sell:           'Sell',
    profile:        'Profile',
    register:       'Sign up',
    createProfile:  'Create my profile',
    alreadyAccount: 'I already have an account',
    myProfile:      'My profile',
    myShop:         'My shop',
    logout:         'Log out',
    location:       'Casablanca • Individual',

    // Auth modal — shared
    back:           'Back',
    next:           'Next',
    validate:       'Confirm',
    loading:        'Loading…',
    orSeparator:    'or',

    // Auth modal — login
    loginTitle:     'Log in',
    loginSubtitle:  'Sign in with your phone number or email',
    identifierLabel: 'Phone or email',
    identifierPlaceholder: '+212 6XX XXX XXX or email@example.com',
    passwordLabel:  'Password',
    passwordPlaceholder: '••••••••',
    loginBtn:       'Log in',
    noAccount:      'No account yet?',
    createAccount:  'Create an account',
    loginWithOtp:   'Log in by SMS',

    // Home — hero
    heroBadge:      'Classifieds',
    heroTitle1:     'Find,',
    heroTitle2:     'sell',
    heroSubtitle:   'Thousands of listings in real estate, cars, jobs and more. Post for free in seconds.',
    heroSearch:     'Apartment, Car, iPhone…',
    statAds:        '+40,000',
    statShops:      '+800',
    statFree:       'Free',
    seeAll:         'See all',
    copyright:      '© 2026 Daba. All rights reserved.',
    madeIn:         'Made with ❤️',

    // Home — features
    feat1Title: 'Photos & Videos',
    feat1Desc:  'Up to 10 photos and YouTube videos for your listings.',
    feat2Title: 'Phone login',
    feat2Desc:  'No password — receive a code by SMS or WhatsApp.',
    feat3Title: 'Pro Shops',
    feat3Desc:  'Create your pro shop and manage all your listings.',
    feat4Title: 'Advanced search',
    feat4Desc:  'Filter by city, price, category and specific attributes.',

    // Home — categories
    catImmobilier:   'Real estate',
    catAutomobile:   'Vehicles',
    catEmploi:       'Jobs',
    catElectronique: 'Electronics',
    catMaison:       'Home',
    catMode:         'Fashion',
    catLoisirs:      'Leisure',
    catServices:     'Services',

    sectionTrending:   'Trending now',
    sectionCars:       'Find your next car',
    sectionRealEstate: 'Real estate picks',
    seeAllAds:         'See all listings',
    searchTitle:    'Search for an item, city or shop',
    searchSubtitle: 'Start searching among thousands of local listings.',
    searchPlaceholder: 'Search for an item, city or shop',
    searchButton: 'Search',
    allCities: 'All cities',
    statsActiveAds: 'active listings',
    statsProShops: 'pro shops',
    statsFree: 'for everyone',
    exploreByCategory: 'Browse by category',
    whyTitle: 'Why Daba?',
    whySubtitle: 'Simple, fast and built for Morocco.',
    ctaBadge: 'Get started',
    ctaTitle: 'Sell in minutes',
    ctaDesc: 'Post your listing for free with photos, or create a pro shop to manage your inventory. Sign in with your phone number — no password.',
    ctaPostAd: 'Post a free listing',
    ctaOpenShop: 'Create a pro shop',
    adsPublished: 'listings posted',
    shopsActive: 'active shops',
    freeForPosting: 'free to post',
    footerDesc: 'The classifieds site and great opportunities. Simple, fast, free.',
    footerCategories: 'Categories',
    footerAccount: 'Account',
    footerLogin: 'Log in',
    footerPostAd: 'Post a listing',
    footerProShops: 'Pro shops',
    vehicles: 'Vehicles',
    realEstate: 'Real estate',
    jobsCategory: 'Jobs',
    promoEyebrow: 'Give your deals a boost',
    promoTitle: 'Sell something. Buy what you need.',
    promoText: 'Post in minutes and reach local buyers for your items, services and offers.',
    sellNow: 'Sell',
    browseAds: 'Browse',
    topAdsTitle: 'Browse the best listings',
    topAdsSubtitle: 'Discover vehicle, real estate and job offers.',
    viewAllCategories: 'View all categories',
    footerBrandText: 'Turn your unused belongings into great deals, simply.',
    footerBrand: 'Daba',
    aboutUs: 'About us',
    press: 'Press',
    careers: 'Careers',
    sustainability: 'Sustainability',
    support: 'Support',
    help: 'Help',
    helpCenter: 'Help center',
    communityGuidelines: 'Community guidelines',
    securityTips: 'Safety tips',
    legal: 'Legal',
    legalSection: 'Legal information',
    legalNotice: 'Legal notice',
    terms: 'Terms',
    privacy: 'Privacy',
    cookies: 'Cookies',
    pro: 'Daba Pro',
    followUs: 'Follow us',

    // Auth modal — register step 1 (credentials)
    registerTitle:     'Create an account',
    registerSubtitle:  'Enter your login information',
    phoneLabel:        'Phone number',
    phonePlaceholder:  '+212 6XX XXX XXX',
    emailLabel:        'Email address',
    emailPlaceholder:  'email@example.com',
    optional:          '(optional)',
    confirmPasswordLabel: 'Confirm password',
    confirmPasswordPlaceholder: '••••••••',
    hasAccount:        'Already have an account?',
    login:             'Log in',

    // Auth modal — register step 2 (identity)
    identityTitle:    'Your identity',
    identitySubtitle: 'How would you like to be displayed?',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'E.g.: Ahmed Benali',

    // Auth modal — register step 3 (address)
    addressTitle:      'Your address',
    addressSubtitle:   'Optional — used to locate your listings',
    addressLabel:      'Address',
    addressPlaceholder: '12 Mohammed V Street',
    cityLabel:         'City',
    cityPlaceholder:   'Casablanca',
    postalCodeLabel:   'Postal code',
    postalCodePlaceholder: '20000',
    countryLabel:      'Country',
    finishBtn:         'Create my account',

    // OTP step
    sendCode:         'Send code',
    otpTitle:         'Verification',
    otpSentTo:        'Code sent to',
    otpLabel:         '6-digit code',
    otpPlaceholder:   '• • • • • •',
    resendCode:       'Resend code',

    // Ads page
    allAds:            'All listings',
    searchAds:         'Search listings…',
    filters:           'Filters',
    filterCategory:    'Category',
    filterSubcategory: 'Subcategory',
    filterCity:        'City',
    filterPriceRange:  'Price range',
    filterMinPrice:    'Min (DH)',
    filterMaxPrice:    'Max (DH)',
    applyFilters:      'Apply',
    resetFilters:      'Reset',
    sortBy:            'Sort by',
    sortNewest:        'Newest first',
    sortPriceAsc:      'Price: Low to High',
    sortPriceDesc:     'Price: High to Low',
    noAdsFound:        'No listings found',
    noAdsFoundSub:     'Try adjusting your filters or search terms.',
    currency:          'DH',
    listingCount:      'listing(s)',
    priceNegotiable:   'Negotiable',
    allSubcategories:  'All subcategories',
    allCategories:     'All categories',
    contactSeller:     'Contact seller',
    backToResults:     'Back to listings',
    adNotFound:        'Listing not found',
    adNotFoundSub:     'This listing no longer exists or has been removed.',
    adDescription:     'Description',
    postedOn:          'Posted on',
    views:             'views',
    share:             'Share',

    // Errors
    errInvalidPhone:    'Invalid phone number',
    errInvalidEmail:    'Invalid email address',
    errPasswordMin:     'Password must be at least 8 characters',
    errPasswordMatch:   'Passwords do not match',
    errDisplayName:     'Please enter a name',
    errIdentifier:      'Phone or email required',
    errInvalidOtp:      'Incorrect or expired code',
    errNetwork:         'Network error, please try again',
    errPhoneOrEmail:    'Phone or email required',
    errCredentials:     'Incorrect credentials',

    // Post Ad
    postAdTitle:        'Post a listing',
    postAdSubtitle:     'Fill in the information below to publish your listing.',
    postAdCategory:     'Category',
    postAdSubcategory:  'Subcategory',
    postAdSelectCat:    'Choose a category',
    postAdSelectSub:    'Choose a subcategory',
    postAdAdTitle:      'Listing title',
    postAdTitlePlaceholder: 'E.g.: iPhone 14 Pro Max 256 GB',
    postAdDescription:  'Description',
    postAdDescPlaceholder: 'Describe your item in detail…',
    postAdPrice:        'Price (MAD)',
    postAdPricePlaceholder: 'E.g.: 1500',
    postAdPriceFree:    'Leave empty if free',
    postAdCity:         'City',
    postAdSelectCity:   'Choose a city',
    postAdSubmit:       'Publish listing',
    postAdSuccess:      'Listing published successfully!',
    postAdLoginRequired: 'You must be logged in to post a listing.',
    errCatRequired:     'Please choose a category',
    errTitleRequired:   'Please enter a title',
    errCityRequired:    'Please choose a city',

    // Warnings
    testingWarning: 'This website is for testing and content is not real ads',
    maintenanceWarning: 'Maintenance in progress - no new ads can be posted',
  },

  ar: {
    // Navbar
    sell:           'بيع',
    profile:        'حسابي',
    register:       'تسجيل',
    createProfile:  'إنشاء حسابي',
    alreadyAccount: 'لدي حساب',
    myProfile:      'ملفي الشخصي',
    myShop:         'متجري',
    logout:         'تسجيل الخروج',
    location:       'الدار البيضاء • فرد',

    // Auth modal — shared
    back:           'رجوع',
    next:           'التالي',
    validate:       'تأكيد',
    loading:        'جاري التحميل…',
    orSeparator:    'أو',

    // Auth modal — login
    loginTitle:     'تسجيل الدخول',
    loginSubtitle:  'سجّل الدخول برقم هاتفك أو بريدك',
    identifierLabel: 'الهاتف أو البريد الإلكتروني',
    identifierPlaceholder: '+212 6XX XXX XXX أو email@example.com',
    passwordLabel:  'كلمة المرور',
    passwordPlaceholder: '••••••••',
    loginBtn:       'تسجيل الدخول',
    noAccount:      'ليس لديك حساب؟',
    createAccount:  'إنشاء حساب',
    loginWithOtp:   'الدخول عبر SMS',

    // Home — hero
    heroBadge:      'إعلانات مبوبة',
    heroTitle1:     'ابحث، بع،',
    heroTitle2:     'تواصل.',
    heroSubtitle:   'آلاف الإعلانات في العقارات والسيارات والوظائف وأكثر. انشر مجاناً في ثوانٍ.',
    heroSearch:     'شقة، سيارة، هاتف…',
    statAds:        '+40 000',
    statShops:      '+800',
    statFree:       'مجاني',
    seeAll:         'عرض الكل',
    copyright:      '© 2026 Daba. جميع الحقوق محفوظة.',
    madeIn:         'صُنع بـ ❤️',

    // Home — features
    feat1Title: 'صور وفيديوهات',
    feat1Desc:  'حتى 10 صور وفيديوهات يوتيوب لإعلاناتك.',
    feat2Title: 'الدخول بالهاتف',
    feat2Desc:  'لا كلمة مرور — استقبل رمزاً عبر SMS أو واتساب.',
    feat3Title: 'متاجر محترفة',
    feat3Desc:  'أنشئ متجرك الاحترافي وأدر جميع إعلاناتك.',
    feat4Title: 'بحث متقدم',
    feat4Desc:  'فلترة حسب المدينة والسعر والفئة والمواصفات.',

    // Home — categories
    catImmobilier:   'العقارات',
    catAutomobile:   'المركبات',
    catEmploi:       'الوظائف',
    catElectronique: 'الإلكترونيات',
    catMaison:       'المنزل',
    catMode:         'الموضة',
    catLoisirs:      'الترفيه',
    catServices:     'الخدمات',

    searchTitle:    'ابحث عن سلعة، مدينة أو متجر',
    searchSubtitle: 'ابدأ البحث بين آلاف الإعلانات المحلية.',

    sectionTrending:   'الأكثر رواجاً',
    sectionCars:       'غيّر سيارتك',
    sectionRealEstate: 'أبرز العقارات',
    seeAllAds:         'عرض جميع الإعلانات',
    searchButton: 'بحث',
    allCities: 'جميع المدن',
    statsActiveAds: 'إعلانات نشطة',
    statsProShops: 'متاجر محترفة',
    statsFree: 'مجاني للجميع',
    exploreByCategory: 'استكشف بحسب الفئة',
    viewAllCategories: 'عرض الكل',
    whyTitle: 'لماذا دبّا؟',
    whySubtitle: 'سهل، سريع، مصمم للمغرب.',
    ctaBadge: 'ابدأ الآن',
    ctaTitle: 'بع في دقائق',
    ctaDesc: 'انشر إعلانك مجاناً مع صور، أو أنشئ متجرًا احترافيًا لإدارة مخزونك. تسجيل الدخول برقم الهاتف — بدون كلمة مرور.',
    ctaPostAd: 'انشر إعلاناً مجاناً',
    ctaOpenShop: 'أنشئ متجرًا احترافياً',
    adsPublished: 'إعلانات منشورة',
    shopsActive: 'متاجر نشطة',
    freeForPosting: 'مجاني للنشر',
    footerDesc: 'موقع الإعلانات المبوبة وفرص كبيرة. سهل، سريع، مجاني.',
    footerCategories: 'الفئات',
    footerAccount: 'الحساب',
    footerLogin: 'تسجيل الدخول',
    footerPostAd: 'نشر إعلان',
    footerProShops: 'متاجر محترفة',
    vehicles: 'المركبات',
    realEstate: 'العقارات',
    jobsCategory: 'الوظائف',
    promoEyebrow: 'اجعل بيعك أسرع',
    promoTitle: 'بع شيئاً تملكه. اشتري ما تحتاجه.',
    promoText: 'نشر إعلانك في دقائق ووصول المشترين المحليين لأغراضك وخدماتك.',
    sellNow: 'بيع',
    browseAds: 'عرض',
    topAdsTitle: 'تصفح أفضل الإعلانات',
    topAdsSubtitle: 'اكتشف عروض السيارات والعقارات والوظائف.',
    footerBrandText: 'حوّل ممتلكاتك غير المستخدمة إلى فرص مربحة بسهولة.',
    footerBrand: 'دبا',
    aboutUs: 'من نحن',
    press: 'الصحافة',
    careers: 'وظائف',
    sustainability: 'الاستدامة',
    support: 'الدعم',
    help: 'مساعدة',
    helpCenter: 'مركز المساعدة',
    communityGuidelines: 'إرشادات المجتمع',
    securityTips: 'نصائح الأمان',
    legal: 'قانوني',
    legalSection: 'معلومات قانونية',
    legalNotice: 'إشعار قانوني',
    terms: 'الشروط',
    privacy: 'الخصوصية',
    cookies: 'ملفات تعريف الارتباط',
    pro: 'دبا برو',
    followUs: 'تابعنا',

    // Auth modal — register step 1 (credentials)
    registerTitle:    'إنشاء حساب',
    registerSubtitle: 'أدخل معلومات تسجيل الدخول',
    phoneLabel:       'رقم الهاتف',
    phonePlaceholder:  '+1 234 567 890',
    emailLabel:       'البريد الإلكتروني',
    emailPlaceholder: 'email@exemple.ma',
    optional:         '(اختياري)',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    confirmPasswordPlaceholder: '••••••••',
    hasAccount:       'لديك حساب بالفعل؟',
    login:            'تسجيل الدخول',

    // Auth modal — register step 2 (identity)
    identityTitle:    'هويتك',
    identitySubtitle: 'كيف تريد أن تظهر للآخرين؟',
    displayNameLabel: 'الاسم المعروض',
    displayNamePlaceholder: 'مثال: أحمد بنعلي',

    // Auth modal — register step 3 (address)
    addressTitle:      'عنوانك',
    addressSubtitle:   'اختياري — يُستخدم لتحديد موقع إعلاناتك',
    addressLabel:      'العنوان',
    addressPlaceholder: '12 شارع محمد الخامس',
    cityLabel:         'المدينة',
    cityPlaceholder:   'الدار البيضاء',
    postalCodeLabel:   'الرمز البريدي',
    postalCodePlaceholder: '20000',
    countryLabel:      'البلد',
    finishBtn:         'إنشاء حسابي',

    // OTP step
    sendCode:         'إرسال الرمز',
    otpTitle:         'التحقق',
    otpSentTo:        'تم إرسال الرمز إلى',
    otpLabel:         'رمز مكون من 6 أرقام',
    otpPlaceholder:   '• • • • • •',
    resendCode:       'إعادة إرسال الرمز',

    // Ads page
    allAds:            'جميع الإعلانات',
    searchAds:         'ابحث عن إعلانات…',
    filters:           'الفلاتر',
    filterCategory:    'الفئة',
    filterSubcategory: 'الفئة الفرعية',
    filterCity:        'المدينة',
    filterPriceRange:  'نطاق السعر',
    filterMinPrice:    'الحد الأدنى (Dh)',
    filterMaxPrice:    'الحد الأقصى (Dh)',
    applyFilters:      'تطبيق',
    resetFilters:      'إعادة ضبط',
    sortBy:            'ترتيب حسب',
    sortNewest:        'الأحدث أولاً',
    sortPriceAsc:      'السعر تصاعدي',
    sortPriceDesc:     'السعر تنازلي',
    noAdsFound:        'لم يتم العثور على إعلانات',
    noAdsFoundSub:     'جرّب تعديل الفلاتر أو مصطلحات البحث.',
    currency:          'Dh',
    listingCount:      'إعلان',
    priceNegotiable:   'قابل للتفاوض',
    allSubcategories:  'جميع الفئات الفرعية',
    allCategories:     'جميع الفئات',
    contactSeller:     'تواصل مع البائع',
    backToResults:     'العودة إلى الإعلانات',
    adNotFound:        'الإعلان غير موجود',
    adNotFoundSub:     'هذا الإعلان لم يعد موجودًا أو تم حذفه.',
    adDescription:     'الوصف',
    postedOn:          'نُشر في',
    views:             'مشاهدة',
    share:             'مشاركة',

    // Errors
    errInvalidPhone:    'رقم الهاتف غير صالح',
    errInvalidEmail:    'البريد الإلكتروني غير صالح',
    errPasswordMin:     'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
    errPasswordMatch:   'كلمتا المرور غير متطابقتين',
    errDisplayName:     'الرجاء إدخال اسم',
    errIdentifier:      'الهاتف أو البريد الإلكتروني مطلوب',
    errInvalidOtp:      'الرمز غير صحيح أو منتهي الصلاحية',
    errNetwork:         'خطأ في الشبكة، حاول مرة أخرى',
    errPhoneOrEmail:    'الهاتف أو البريد الإلكتروني مطلوب',
    errCredentials:     'بيانات الاعتماد غير صحيحة',

    // Post Ad
    postAdTitle:        'نشر إعلان',
    postAdSubtitle:     'أدخل المعلومات التالية لنشر إعلانك.',
    postAdCategory:     'الفئة',
    postAdSubcategory:  'الفئة الفرعية',
    postAdSelectCat:    'اختر فئة',
    postAdSelectSub:    'اختر فئة فرعية',
    postAdAdTitle:      'عنوان الإعلان',
    postAdTitlePlaceholder: 'مثال: آيفون 14 برو ماكس 256 جيجا',
    postAdDescription:  'الوصف',
    postAdDescPlaceholder: 'صف غرضك بالتفصيل…',
    postAdPrice:        'السعر (درهم)',
    postAdPricePlaceholder: 'مثال: 1500',
    postAdPriceFree:    'اتركه فارغاً إذا كان مجانياً',
    postAdCity:         'المدينة',
    postAdSelectCity:   'اختر مدينة',
    postAdSubmit:       'نشر الإعلان',
    postAdSuccess:      'تم نشر الإعلان بنجاح!',
    postAdLoginRequired: 'يجب تسجيل الدخول لنشر إعلان.',
    errCatRequired:     'الرجاء اختيار فئة',
    errTitleRequired:   'الرجاء إدخال عنوان',
    errCityRequired:    'الرجاء اختيار مدينة',

    // Warnings
    testingWarning: 'هذا الموقع مخصص للاختبار والمحتوى ليس إعلانات حقيقية',
    maintenanceWarning: 'صيانة قيد التقدم - لا يمكن نشر إعلانات جديدة',
  },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private readonly platformId = inject(PLATFORM_ID);

  readonly current  = signal<Lang>('fr');
  readonly isRtl    = computed(() => this.current() === 'ar');
  readonly languages = LANGUAGES;

  t(key: string): string {
    return TRANSLATIONS[this.current()][key] ?? key;
  }

  currentLang() {
    return LANGUAGES.find(l => l.code === this.current())!;
  }

  setLang(lang: Lang): void {
    this.current.set(lang);
    if (isPlatformBrowser(this.platformId)) {
      const def = LANGUAGES.find(l => l.code === lang)!;
      document.documentElement.lang = lang;
      document.documentElement.dir  = def.dir;
    }
  }
}
